"""occurrences_capture.py -- every DRAWN occurrence of the CAPTURE PACKET's 12 born-digital exhibit
pages (P1.8 / T1.3(a); `31-` SSC.1 rows 05-16). A SEPARATE registry from `occurrences.ALL`, which is
scoped to what `packet.pdf` draws (D12-40): joining these to that registry would rewrite the packet.

Tier discipline is the packet's: a tier names the MECHANISM and the SCORE that earn it, against the
balanced preset (ssn 0.60 · name 0.60 · dob 0.30 · address 0.60 · phone 0.70 · email 0.83 ·
account 0.60 · routingNumber 0.60 · ein 0.55 · creditCard 0.88 · driversLicense 0.72 · passport 0.72
· mrn 0.60 · npi 0.602 · dea 0.60 · licensePlate 0.65). Doctype gates (PIIDetector.detect):
DOB label-anchored-only on .financial (0.85) / full DOBDetector elsewhere (0.05 + 0.30 label within
+-80 chars + 0.15 age on line); MRN + DEA medical-only; NPI medical + foia; account financial /
medical / court / generic; routing financial / generic; licensePlate court / foia / generic.
Names: NLTagger pass (0.70) -- the host `NLTagger(.nameType)` probe of 2026-08-24 is cited where it
decided a tier -- plus the legal-prefix pass (Plaintiff / Defendant / Judge / Patient / Witness /
Dr. / Ms. ... -> 0.65). ALL-CAPS names ride the strict shadow pass whose bloom membership is not
verified here -> should_fire, the packet precedent. `image`-leg rows (barcode, signature stroke)
are Vision-side detectors the Scan text/OCR legs never run -> watch.

Every character is printable ASCII. Tier codes: MF/SF/W/MNF -> must_fire/should_fire/watch/
must_not_fire.
"""

from __future__ import annotations

from . import personas as P
from .manifest import Occurrence as O

# ==================================================================================================
# M1 -- benefits-determination letter behind a #10 window-envelope USPS block (.financial)
# ==================================================================================================
M1 = [
    O(
        "occ_m1_01",
        P.NADIA_NAME_CAPS,
        "name",
        "mail_m1",
        "SF",
        "",
        all_caps=True,
        justification="USPS Pub 28 window-block surface, ALL-CAPS, no label: NLTagger pass-1 miss on ALL-CAPS; the strict shadow pass needs surname+given bloom hits (unverified) -> should_fire.",
    ),
    O(
        "occ_m1_02",
        P.ADDR_NADIA_USPS,
        "address",
        "mail_m1",
        "MF",
        "",
        multiline=True,
        all_caps=True,
        justification="ALL-CAPS USPS lines: the regex arm MISSES (street-suffix alternation is case-sensitive, 'DR' != 'Dr'); the AddressSpatialAssembler arm fires: (?i) street line '2210 LARKSPUR DR', ZIP anchor 83646, word-bounded 'ID' state, SCF 836 -> ID cross-check -> 0.80 >= 0.60; no comma -> no city cross-check. 2 spans.",
    ),
    O(
        "occ_m1_03",
        P.NADIA_NAME,
        "name",
        "mail_m1",
        "MF",
        "Claimant Name:",
        justification="clean two-token Title-Case; NLTagger host probe tags 'Claimant Name: Nadia Petrova' -> 0.70 >= 0.60.",
    ),
    O(
        "occ_m1_04",
        P.NADIA_DOB,
        "dateOfBirth",
        "mail_m1",
        "MF",
        "Date of Birth:",
        justification="label-anchored numeric on .financial (D4 path, dobPattern adjacency) -> 0.85 >= 0.30.",
    ),
    O(
        "occ_m1_05",
        P.NADIA_BENEFIT_ACCT,
        "account",
        "mail_m1",
        "MF",
        "Benefit Account No.:",
        justification="12-digit (phone-immune, < 13-digit cc); 'account' kw within +-5 tokens -> boosted 0.58 raw, posterior clears 0.60 (packet occ_urlab_15 precedent, strict-true at P1.2). No routing kw within +-8.",
    ),
    O(
        "occ_m1_06",
        P.NADIA_PHONE_HOME,
        "phone",
        "mail_m1",
        "MF",
        "Questions? Call",
        justification="NANP 555-01xx; 'call' positive kw within +-80 chars -> 0.80 >= 0.70.",
    ),
    O(
        "occ_m1_07",
        P.LETTER_DATE,
        "dateOfBirth",
        "mail_m1",
        "MNF",
        "Date:",
        justification="bare letter date on .financial: only the label-anchored dobPattern runs and 'Date:' is not a DOB label -> no candidate.",
    ),
    O(
        "occ_m1_08",
        P.OFFICE_CODE,
        "other",
        "mail_m1",
        "MNF",
        "Office Code:",
        justification="'0417-B': 4 digits + letter -- below every numeric detector's minimum run (account needs 6, phone 10, ssn 9) and no labeled-id pattern -> no detector has a candidate.",
    ),
    O(
        "occ_m1_09",
        P.CLAIM_REF_10,
        "phone",
        "mail_m1",
        "MNF",
        "Reference No.",
        justification="10 contiguous digits match the separator-optional phone regex, but no positive phone kw (phone/tel/call/contact/number/...) within +-80 chars -> bare 0.60 < 0.70; 'reference no' is also a phone NEGATIVE. Account: no acct kw within +-5 -> base 0.",
    ),
]

# ==================================================================================================
# M2 -- utility bill with remittance stub (.financial)
# ==================================================================================================
M2 = [
    O(
        "occ_m2_01",
        P.NADIA_UTIL_ACCT,
        "account",
        "mail_m2",
        "MF",
        "Account No.",
        justification="12-digit; 'account' kw adjacent (+-5) -> boosted; posterior clears 0.60 (occ_urlab_15 precedent). Kept > 8 tokens from any routing kw.",
    ),
    O(
        "occ_m2_02",
        P.NADIA_NAME,
        "name",
        "mail_m2",
        "MF",
        "Customer Name:",
        justification="clean two-token Title-Case; NLTagger host probe tags 'Customer Name: Nadia Petrova' -> 0.70.",
    ),
    O(
        "occ_m2_03",
        P.ADDR_NADIA,
        "address",
        "mail_m2",
        "MF",
        "Service Address:",
        multiline=True,
        justification="Title-Case 'Drive' + 'ID 83646': regex arm -> 0.70; assembler arm also fires. 2 spans.",
    ),
    O(
        "occ_m2_04",
        P.NADIA_PHONE_HOME,
        "phone",
        "mail_m2",
        "MF",
        "Telephone on file:",
        justification="'tel' substring positive within +-80 chars -> 0.80.",
    ),
    O(
        "occ_m2_05",
        P.UTILITY_PHONE,
        "phone",
        "mail_m2",
        "MF",
        "Billing questions? Call",
        justification="the utility's own billing line (an org phone; fires as phone all the same); 'call' positive within +-80 chars -> 0.80. One minted number per org: the housing authority's reviewer line stays on M3/M4, so a value colliding across two unrelated orgs can never make a cross-page analysis ambiguous.",
    ),
    O(
        "occ_m2_06",
        P.METER_NO,
        "account",
        "mail_m2",
        "MNF",
        "Meter No.",
        justification="8-digit run is an account-regex candidate, but no acct kw within +-5 tokens -> base 0.0 -> dropped at the > 0 guard. Not 9/10 digits -> no ssn/phone/routing candidate.",
    ),
    O(
        "occ_m2_07",
        P.STMT_NO,
        "account",
        "mail_m2",
        "MNF",
        "Statement No.",
        justification="'20260811-77': the 8-digit run is an account-regex candidate with no acct kw within +-5 -> base 0. Earns the financial invoice_label bonus (classification), not a fire.",
    ),
    O(
        "occ_m2_08",
        P.DUE_DATE,
        "dateOfBirth",
        "mail_m2",
        "MNF",
        "Due Date:",
        justification="bare date on .financial; 'Due Date' is not a DOB label -> the label-anchored path has no candidate.",
    ),
    O(
        "occ_m2_09",
        P.NADIA_CARD_MASKED,
        "creditCard",
        "mail_m2",
        "W",
        "Autopay card on file:",
        masked=True,
        justification="masked '**** 4421' < 13 digits -> below the cc shape; masked watch (occ_urlab_20 precedent).",
    ),
]

# ==================================================================================================
# M3 -- housing-assistance application / intake form, FLAT print master (.financial)
# ==================================================================================================
M3 = [
    O(
        "occ_m3_01",
        P.NADIA_NAME,
        "name",
        "forms_m3",
        "MF",
        "Applicant Name:",
        justification="clean two-token Title-Case; NLTagger host probe tags 'Applicant Name: Nadia Petrova' -> 0.70.",
    ),
    O(
        "occ_m3_02",
        P.NADIA_DOB,
        "dateOfBirth",
        "forms_m3",
        "MF",
        "Date of Birth:",
        justification="label-anchored numeric on .financial -> 0.85.",
    ),
    O(
        "occ_m3_03",
        P.NADIA_DOB,
        "dateOfBirth",
        "forms_m3",
        "SF",
        "Date of Birth (mm/dd/yyyy):",
        justification="the boxed-form hint '(mm/dd/yyyy)' sits between label and date, breaking dobPattern adjacency -> text-leg miss (occ_urlab_04 precedent) -> should_fire. Same DOB as occ_02.",
    ),
    O(
        "occ_m3_04",
        P.NADIA_SSN,
        "ssn",
        "forms_m3",
        "MF",
        "Social Security Number:",
        source_range="synthetic + manifest (no provable never-issued SSN space post-2011)",
        justification="area 512, group 40, serial 7781 valid; 'social security' positive within +-5 -> 0.95. Kept > 5 tokens from the financial ssn negatives (account number / claim number).",
    ),
    O(
        "occ_m3_05",
        P.NADIA_DL,
        "driversLicense",
        "forms_m3",
        "MF",
        "Driver's License No:",
        justification="label 'Driver's License' + 1L+7D -> CA ^[A-Z][0-9]{7}$ gazetteer row -> 0.80 >= 0.72.",
    ),
    O(
        "occ_m3_06",
        P.NADIA_PHONE_CELL,
        "phone",
        "forms_m3",
        "MF",
        "Cell Phone:",
        justification="'phone'/'cell' positive -> 0.80.",
    ),
    O(
        "occ_m3_07",
        P.NADIA_EMAIL,
        "email",
        "forms_m3",
        "MF",
        "Email:",
        justification="RFC-2606 -> 0.90 >= 0.83.",
    ),
    O(
        "occ_m3_08",
        P.ADDR_NADIA,
        "address",
        "forms_m3",
        "MF",
        "Current Address:",
        multiline=True,
        justification="Title-Case regex arm -> 0.70; 2 spans.",
    ),
    O(
        "occ_m3_09",
        P.APP_ID,
        "other",
        "forms_m3",
        "MNF",
        "Application ID:",
        justification="'HA-2026-004471': no contiguous 6-digit run (account), no 'No.'-prefixed docket shape, letters-dash-digits with a 4-digit block breaks the MRN institution shape -> no detector candidate.",
    ),
    O(
        "occ_m3_10",
        P.DATE_SIGNED_M3,
        "dateOfBirth",
        "forms_m3",
        "MNF",
        "Date Signed:",
        justification="bare signature date on .financial -> suppressed (label-anchored-only gate).",
    ),
]

# ==================================================================================================
# M4 -- fax cover sheet + transmittal (.generic; the fax-class master)
# ==================================================================================================
M4 = [
    O(
        "occ_m4_01",
        P.NAOMI_NAME,
        "name",
        "forms_m4",
        "MF",
        "Recipient Name:",
        justification="clean two-token Title-Case; NLTagger host probe tags the reviewer's name in this label form -> 0.70.",
    ),
    O(
        "occ_m4_02",
        P.NADIA_NAME,
        "name",
        "forms_m4",
        "MF",
        "Sender Name:",
        justification="clean two-token Title-Case; NLTagger host probe -> 0.70.",
    ),
    O(
        "occ_m4_03",
        P.NAOMI_FAX,
        "phone",
        "forms_m4",
        "MF",
        "Recipient Fax:",
        justification="fax-shaped NANP; 'fax' is a phone positive kw -> 0.80 (the engine has no fax kind: category phone).",
    ),
    O(
        "occ_m4_04",
        P.NAOMI_PHONE,
        "phone",
        "forms_m4",
        "MF",
        "Recipient Phone:",
        justification="'phone' positive -> 0.80.",
    ),
    O(
        "occ_m4_05",
        P.NADIA_FAX,
        "phone",
        "forms_m4",
        "MF",
        "Sender Fax:",
        justification="'fax' positive -> 0.80.",
    ),
    O(
        "occ_m4_06",
        P.NADIA_PHONE_WORK,
        "phone",
        "forms_m4",
        "MF",
        "Sender Phone:",
        justification="dotted format zoo; 'phone' positive -> 0.80.",
    ),
    O(
        "occ_m4_07",
        P.FAX_SENT_DATE,
        "dateOfBirth",
        "forms_m4",
        "MNF",
        "Date Sent:",
        justification="page classifies .generic -> full DOBDetector: numeric base 0.05, no DOB label within +-80 chars, no 'age' on the line -> 0.05 < 0.30.",
    ),
    O(
        "occ_m4_08",
        P.FAX_REF,
        "other",
        "forms_m4",
        "MNF",
        "Transmittal Ref:",
        justification="'TX-26-0447': letters-dash-2-digits-dash-4-digits -- no numeric run >= 6, no labeled-id shape -> no candidate.",
    ),
    O(
        "occ_m4_09",
        P.FAX_ACCT_REF,
        "account",
        "forms_m4",
        "MNF",
        "Account Ref:",
        justification="'account' kw present but '4471-0293' has no contiguous >= 6-digit run -> the account regex has no candidate; 4-digit halves are below every other minimum.",
    ),
]

# ==================================================================================================
# K1 -- pleading-paper caption page, 28 numbered lines (.court)
# ==================================================================================================
K1 = [
    O(
        "occ_k1_01",
        P.MARCUS_NAME_CAPS,
        "name",
        "court_k1",
        "SF",
        "",
        all_caps=True,
        justification="caption party in ALL-CAPS: NLTagger pass-1 miss; strict shadow pass needs bloom hits (unverified); 'Plaintiff' follows the name so the legal-prefix pass finds nothing after it -> should_fire.",
        context_class="caption_left",
    ),
    O(
        "occ_k1_02",
        P.TERRENCE_NAME_CAPS,
        "name",
        "court_k1",
        "SF",
        "",
        all_caps=True,
        justification="caption defendant in ALL-CAPS, same mechanism -> should_fire.",
        context_class="caption_right",
    ),
    O(
        "occ_k1_03",
        P.PRIYA_NAME,
        "name",
        "court_k1",
        "MF",
        "Attorney for Plaintiff:",
        justification="NLTagger host probe tags 'Attorney for Plaintiff: Priya Ramaswamy' (0.70); the 'Plaintiff' legal-prefix pass also yields it at 0.65.",
        context_class="role_label",
    ),
    O(
        "occ_k1_04",
        P.ADDR_FIRM,
        "address",
        "court_k1",
        "MF",
        "",
        multiline=True,
        justification="Title-Case '1100 Idaho Street, Suite 400' + 'Boise, ID 83702' -> regex arm 0.70 (.{0,100}? bridges the suite + newline); 2 spans.",
    ),
    O(
        "occ_k1_05",
        P.FIRM_PHONE,
        "phone",
        "court_k1",
        "MF",
        "Telephone:",
        justification="'tel' positive -> 0.80.",
    ),
    O(
        "occ_k1_06",
        P.PRIYA_EMAIL,
        "email",
        "court_k1",
        "MF",
        "Email:",
        justification="RFC-2606 -> 0.90.",
    ),
    O(
        "occ_k1_07",
        P.PRIYA_BAR,
        "account",
        "court_k1",
        "MNF",
        "Idaho State Bar No.",
        justification="6-digit run: an account-regex candidate (account RUNS on .court, CND-10) with no acct kw within +-5 -> base 0 -> dropped. No 9/10-digit shape.",
    ),
    O(
        "occ_k1_08",
        P.CASE_NO,
        "other",
        "court_k1",
        "MNF",
        "Case No.",
        justification="'26-CV-01842' has no PII shape; 'case no' is a phone + ssn NEGATIVE anyway. Earns the court docket_number bonus (classification).",
    ),
    O(
        "occ_k1_09",
        P.FILED_DATE,
        "dateOfBirth",
        "court_k1",
        "MNF",
        "Filed:",
        justification=".court -> full DOBDetector: base 0.05, no DOB label within +-80 chars -> 0.05 < 0.30.",
    ),
    O(
        "occ_k1_10",
        P.MARCUS_NAME,
        "name",
        "court_k1",
        "MF",
        "Plaintiff",
        justification="body line 'Plaintiff Marcus Bellamy resides at ...': the legal-prefix pass takes the Title-Case words after 'Plaintiff' until a lowercase token ('resides') -> 0.65 >= 0.60; the NLTagger host probe also tags it (0.70).",
        context_class="role_label",
    ),
    O(
        "occ_k1_11",
        P.ADDR_MARCUS_LINE,
        "address",
        "court_k1",
        "MF",
        "resides at",
        justification="inline single-line Title-Case '4415 Camas Lane, Boise, ID 83705' -> regex arm 0.70.",
    ),
    O(
        "occ_k1_12",
        P.JUDGE_NAME,
        "name",
        "court_k1",
        "MF",
        "Assigned to: Judge",
        justification="'Judge' legal prefix -> 0.65; NLTagger host probe tags 'Assigned to: Judge Beatrice Lindqvist' (0.70).",
        context_class="title_label",
    ),
    O(
        "occ_k1_13",
        P.TERRENCE_NAME,
        "name",
        "court_k1",
        "MF",
        "Defendant",
        justification="body line 'Defendant Terrence Whitfield is an individual who ...': the legal-prefix pass takes the Title-Case words after 'Defendant' until a lowercase token ('is') -> 0.65 >= 0.60; the NLTagger host re-probe of 2026-08-25 also tags the sentence (0.70). The same two-arm mechanism as occ_k1_10 on the plaintiff line.",
        context_class="role_label",
    ),
]

# ==================================================================================================
# K2 -- deposition exhibit page with Bates + exhibit stamp (.court)
# ==================================================================================================
K2 = [
    O(
        "occ_k2_01",
        P.MARCUS_NAME,
        "name",
        "court_k2",
        "MF",
        "Deponent:",
        justification="NLTagger host probe tags 'Deponent: Marcus Bellamy' -> 0.70.",
        context_class="role_label",
    ),
    O(
        "occ_k2_02",
        P.MARCUS_NAME,
        "name",
        "court_k2",
        "MF",
        "A. My name is",
        justification="testimony sentence; NLTagger host probe tags 'My name is Marcus Bellamy.' -> 0.70.",
        context_class="body_prose",
    ),
    O(
        "occ_k2_03",
        P.MARCUS_DOB_TEXTUAL,
        "dateOfBirth",
        "court_k2",
        "MF",
        "my date of birth is",
        justification=".court -> full DOBDetector textual path ('September 9, 1983', year in 1900-2030): base 0.05 + 0.30 ('date of birth' within +-80 chars) = 0.35 >= 0.30 (0.05 margin, the occ_govid_03 precedent on a non-financial page).",
    ),
    O(
        "occ_k2_04",
        P.MARCUS_SSN_LAST4,
        "ssn",
        "court_k2",
        "MNF",
        "the last four digits of my Social Security number are",
        justification="4 digits only: the SSN state machine needs a 9-digit shape -> no candidate despite the 'social security' positive.",
    ),
    O(
        "occ_k2_05",
        P.ADDR_MARCUS_LINE,
        "address",
        "court_k2",
        "MF",
        "I live at",
        justification="single-line Title-Case 'Lane' + 'ID 83705' -> regex arm 0.70.",
    ),
    O(
        "occ_k2_06",
        P.MARCUS_PHONE_CELL,
        "phone",
        "court_k2",
        "MF",
        "my cell is",
        justification="'cell' positive within +-80 chars -> 0.80.",
    ),
    O(
        "occ_k2_07",
        P.TERRENCE_NAME,
        "name",
        "court_k2",
        "MF",
        "my supervisor,",
        justification="NLTagger host probe tags 'my supervisor, Terrence Whitfield, told me' -> 0.70.",
        context_class="body_prose",
    ),
    O(
        "occ_k2_08",
        P.BATES,
        "medicalRecord",
        "court_k2",
        "MNF",
        "",
        justification="Bates 'BELL-0000123' matches the MRN institution shape [A-Z]{2,5}-\\d{6,10}, but runsMRN is medical-only -> the detector never runs on .court (doctype-gated, the occ_urlab_24 mechanism).",
    ),
    O(
        "occ_k2_09",
        P.CASE_NO,
        "other",
        "court_k2",
        "MNF",
        "Case No.",
        justification="no PII shape; phone/ssn negative context.",
    ),
    O(
        "occ_k2_10",
        P.DEPO_DATE,
        "dateOfBirth",
        "court_k2",
        "MNF",
        "Deposition taken",
        justification="full DOBDetector: base 0.05, kept > 80 chars from the testimony's 'date of birth' label -> 0.05 < 0.30.",
    ),
]

# ==================================================================================================
# K3 -- FOIA release page with (b)(6) / (b)(7)(C) bars (.foia; the already-redacted-input case)
# ==================================================================================================
K3 = [
    O(
        "occ_k3_01",
        P.REDACTED_NAME_B6,
        "name",
        "court_k3",
        "MNF",
        P.EXEMPTION_B6,
        masked=True,
        justification="ALREADY REDACTED: a black bar is drawn where the name would be and the text is never emitted -- nothing exists for either leg to fire on. GT keeps the hidden value + bar rect so an evaluator can assert silence there.",
    ),
    O(
        "occ_k3_02",
        P.REDACTED_NAME_B7C,
        "name",
        "court_k3",
        "MNF",
        P.EXEMPTION_B7C,
        masked=True,
        justification="ALREADY REDACTED under a (b)(7)(C) bar; no text under the bar.",
    ),
    O(
        "occ_k3_03",
        P.REDACTED_SSN,
        "ssn",
        "court_k3",
        "MNF",
        P.EXEMPTION_B6,
        masked=True,
        justification="ALREADY REDACTED under a (b)(6) bar; no text under the bar.",
    ),
    O(
        "occ_k3_04",
        P.PRIYA_NAME,
        "name",
        "court_k3",
        "MF",
        "Name of Requester:",
        justification="clean two-token Title-Case under the 'Name of ...' label form the NLTagger host probe tags -> 0.70 (re-probed on the page text).",
    ),
    O(
        "occ_k3_05",
        P.DANA_NAME,
        "name",
        "court_k3",
        "MF",
        "Sincerely,",
        justification="signature block; NLTagger host probe tags 'Sincerely, Dana Whitcombe' -> 0.70.",
        context_class="closing_line",
    ),
    O(
        "occ_k3_06",
        P.DANA_PHONE,
        "phone",
        "court_k3",
        "MF",
        "Telephone:",
        justification="'tel' positive -> 0.80; phone has no doctype gate.",
    ),
    O(
        "occ_k3_07",
        P.ROSTER_NPI,
        "npi",
        "court_k3",
        "MF",
        "Provider NPI:",
        justification="10 digits starting 1, Luhn-80840 valid; runsNPI includes .foia; 'npi' positive within +-5 -> 0.90 >= 0.602.",
    ),
    O(
        "occ_k3_08",
        P.EXEMPTION_B7C,
        "other",
        "court_k3",
        "MNF",
        "Exemptions cited:",
        justification="'(b)(7)(C)': an exemption citation, no PII shape; drives the foia exemption_citation bonus.",
    ),
    O(
        "occ_k3_09",
        P.FOIA_REQ_NO,
        "other",
        "court_k3",
        "MNF",
        "FOIA Request No.",
        justification="'2026-01447': 4+5 digits split by a dash -- no >= 6-digit run, no ssn/phone shape; drives the foia_header bonus.",
    ),
    O(
        "occ_k3_10",
        P.FOIA_DATE,
        "dateOfBirth",
        "court_k3",
        "MNF",
        "",
        justification=".foia -> full DOBDetector textual path: 'August 14, 2026' base 0.05, no DOB label within +-80 chars -> 0.05 < 0.30.",
    ),
    O(
        "occ_k3_11",
        P.ADDR_AGENCY,
        "address",
        "court_k3",
        "MF",
        "",
        multiline=True,
        justification="agency letterhead address, Title-Case 'Avenue' + 'VA 22201' -> regex arm 0.70 (fixed; the (address, foia) gazetteer only scales scorer-based detectors); 2 spans.",
    ),
]

# ==================================================================================================
# K4 -- docket / judgment sheet, dense multi-column (.court)
# ==================================================================================================
K4 = [
    O(
        "occ_k4_01",
        P.MARCUS_NAME,
        "name",
        "court_k4",
        "MF",
        "Plaintiff / Creditor:",
        justification="'Plaintiff' legal prefix -> the Title-Case words after it -> 0.65 >= 0.60 (the probe does not tag 'Judgment Creditor:' forms, so the label leads with the prefix word).",
        context_class="role_label",
    ),
    O(
        "occ_k4_02",
        P.TERRENCE_NAME,
        "name",
        "court_k4",
        "MF",
        "Defendant / Debtor:",
        justification="'Defendant' legal prefix -> 0.65; NLTagger host probe also tags 'Judgment Debtor: Terrence Whitfield' (0.70).",
        context_class="role_label",
    ),
    O(
        "occ_k4_03",
        P.ADDR_TERRENCE,
        "address",
        "court_k4",
        "MF",
        "Debtor Address:",
        multiline=True,
        justification="Title-Case 'Road, Suite 210' + 'Boise, ID 83709' -> regex arm 0.70; 2 spans.",
    ),
    O(
        "occ_k4_04",
        P.MARCUS_DOB,
        "dateOfBirth",
        "court_k4",
        "MF",
        "DOB:",
        justification=".court -> full DOBDetector: 0.05 + 0.30 ('dob' label within +-80 chars) = 0.35 >= 0.30. Isolated in a party-identification block > 80 chars from the docket dates.",
    ),
    O(
        "occ_k4_05",
        P.GARN_ACCT,
        "account",
        "court_k4",
        "MF",
        "Garnishee Account No.",
        justification="12-digit; account RUNS on .court (CND-10); 'account' kw within +-5 -> boosted; posterior clears 0.60 (occ_urlab_15 precedent).",
    ),
    O(
        "occ_k4_06",
        P.CLERK_PHONE,
        "phone",
        "court_k4",
        "MF",
        "Clerk's Office Tel:",
        justification="'tel' positive -> 0.80.",
    ),
    O(
        "occ_k4_07",
        P.CLERK_NAME,
        "name",
        "court_k4",
        "MF",
        "Prepared by:",
        justification="NLTagger host probe tags 'Prepared by: Helen Marchetti' -> 0.70.",
    ),
    O(
        "occ_k4_08",
        P.CASE_NO,
        "other",
        "court_k4",
        "MNF",
        "Case No.",
        justification="no PII shape; docket_number bonus only.",
    ),
    O(
        "occ_k4_09",
        P.JUDGMENT_SUM,
        "other",
        "court_k4",
        "MNF",
        "Judgment sum:",
        justification="currency amount: no detector shape ('$4,250.00' is 4+2 digits split by ',' and '.'); drives the financial currency_amount bonus, which .court still strictly beats.",
    ),
    O(
        "occ_k4_10",
        P.JUDGMENT_DATE,
        "dateOfBirth",
        "court_k4",
        "MNF",
        "Entered",
        justification="full DOBDetector base 0.05; no DOB label within +-80 chars (the DOB block is isolated) -> 0.05 < 0.30.",
    ),
    O(
        "occ_k4_11",
        P.FILED_DATE,
        "dateOfBirth",
        "court_k4",
        "MNF",
        "Filed",
        justification="same mechanism as occ_10 (docket-column date).",
    ),
]

# ==================================================================================================
# H1 -- claim-form-STRUCTURED page (CMS-1500 field STRUCTURE only; never pixel-accurate) (.medical)
# ==================================================================================================
H1 = [
    O(
        "occ_h1_01",
        P.ROSALIND_NAME,
        "name",
        "medical_h1",
        "MF",
        "Patient:",
        justification="'Patient' legal-prefix pass -> 0.65 (a lowercase token follows the name so the box stays clean); NLTagger host probe tags 'Patient: Rosalind Okafor (self)' (0.70).",
        context_class="role_label",
    ),
    O(
        "occ_h1_02",
        P.ROSALIND_DOB,
        "dateOfBirth",
        "medical_h1",
        "MF",
        "Patient Date of Birth:",
        justification=".medical -> full DOBDetector: 0.05 + 0.30 (label within +-80) = 0.35 >= 0.30; 'Age:' on the line adds 0.15 -> 0.50.",
    ),
    O(
        "occ_h1_03",
        P.ROSALIND_MRN,
        "medicalRecord",
        "medical_h1",
        "MF",
        "MRN:",
        justification="mrn.labeled \\bMR[N]?[:#\\s]+[A-Z0-9]{5,12}; runsMRN on .medical; 'patient'/'dob' positives within +-5 tokens -> 0.92 >= 0.60. 8 digits: no ssn/phone/npi shape; no acct kw within +-5.",
    ),
    O(
        "occ_h1_04",
        P.INSURED_ID,
        "account",
        "medical_h1",
        "MNF",
        "Insured ID:",
        justification="'XKE44027191' is an account-regex candidate ([A-Z]{0,3}\\d{6,15}) with no acct kw within +-5 -> base 0 -> dropped; 8 digits -> no ssn; not MRN-shaped (no dash).",
    ),
    O(
        "occ_h1_05",
        P.THORNE_NPI,
        "npi",
        "medical_h1",
        "MF",
        "Rendering Provider NPI:",
        justification="[12]\\d{9} + Luhn-80840 valid; 'npi' positive within +-5 -> 0.90 >= 0.602 (base alone would be 0.65).",
    ),
    O(
        "occ_h1_06",
        P.CLINIC_NPI,
        "npi",
        "medical_h1",
        "MF",
        "Billing Provider NPI:",
        justification="type-2 NPI, Luhn-80840 valid; 'npi' positive -> 0.90.",
    ),
    O(
        "occ_h1_07",
        P.NPI_LUHN_FAIL,
        "npi",
        "medical_h1",
        "MNF",
        "Referring Provider NPI:",
        justification="check digit off by one -> NPILuhn80840.isValid false -> rejected before scoring, despite the label.",
    ),
    O(
        "occ_h1_08",
        P.ROSALIND_PHONE,
        "phone",
        "medical_h1",
        "MF",
        "Patient Telephone:",
        justification="'tel' positive -> 0.80.",
    ),
    O(
        "occ_h1_09",
        P.ADDR_ROSALIND,
        "address",
        "medical_h1",
        "MF",
        "Patient Address:",
        multiline=True,
        justification="Title-Case '87 Juniper Court' + 'Nampa, ID 83651' -> regex arm 0.70; 2 spans.",
    ),
    O(
        "occ_h1_10",
        P.THORNE_NAME,
        "name",
        "medical_h1",
        "MF",
        "Rendering Provider: Dr.",
        justification="'Dr.' legal prefix -> 0.65; NLTagger host probe tags 'Rendering Provider: Dr. Imani Thorne (MD)' (0.70). Parenthesised credential keeps the prefix pass from absorbing it.",
        context_class="title_label",
    ),
    O(
        "occ_h1_11",
        P.ROSALIND_PATIENT_ACCT,
        "account",
        "medical_h1",
        "MF",
        "Patient Account No.",
        justification="7-digit run; account RUNS on .medical; 'account' kw adjacent -> boosted; posterior clears 0.60 (occ_urlab_15 precedent).",
    ),
    O(
        "occ_h1_12",
        P.ICD_CODE,
        "other",
        "medical_h1",
        "MNF",
        "Diagnosis Code:",
        justification="'E11.9': letter + 2 digits + decimal -- no PII shape; drives the medical icd_shape bonus.",
    ),
    O(
        "occ_h1_13",
        P.CLAIM_CONTROL,
        "medicalRecord",
        "medical_h1",
        "MNF",
        "Claim Control No.",
        justification="'HCF-2026041' matches the MRN institution shape and MRN runs here, but NO MRN positive kw (patient/mrn/chart/dob/physician/hospital/diagnosis/...) within +-5 tokens -> base 0.55 < 0.60.",
    ),
    O(
        "occ_h1_14",
        "",
        "signatureCandidate",
        "medical_h1",
        "W",
        "Signature:",
        leg=("image",),
        justification="a drawn stroke beside an exact 'Signature:' OCR block: the DRAW-3 heuristic (Sobel density + curvature on the region right of the label) is triage-only, never auto-applied, and runs on the page image -- not a Scan text/OCR leg -> image leg, watch.",
    ),
]

# ==================================================================================================
# H2 -- clinical visit summary: header block + narrative + prescription line (.medical)
# ==================================================================================================
H2 = [
    O(
        "occ_h2_01",
        P.ROSALIND_NAME,
        "name",
        "medical_h2",
        "MF",
        "Patient:",
        justification="'Patient' legal-prefix pass -> 0.65; NLTagger host probe tags it (0.70).",
        context_class="role_label",
    ),
    O(
        "occ_h2_02",
        P.ROSALIND_MRN,
        "medicalRecord",
        "medical_h2",
        "MF",
        "MRN:",
        justification="mrn.labeled; 'patient'/'dob' within +-5 tokens -> 0.92.",
    ),
    O(
        "occ_h2_03",
        P.ROSALIND_PATIENT_ID,
        "medicalRecord",
        "medical_h2",
        "MF",
        "Patient ID:",
        justification="mrn.patientID \\bPatient\\s+ID[:#\\s]+[A-Z0-9]{5,12}; 'patient' is itself a positive -> 0.92.",
    ),
    O(
        "occ_h2_04",
        P.ROSALIND_DOB,
        "dateOfBirth",
        "medical_h2",
        "MF",
        "DOB:",
        justification="full DOBDetector: 0.05 + 0.30 ('dob' within +-80 chars) = 0.35 >= 0.30.",
    ),
    O(
        "occ_h2_05",
        P.THORNE_NPI,
        "npi",
        "medical_h2",
        "MF",
        "Attending NPI:",
        justification="Luhn-80840 valid; 'npi' positive -> 0.90.",
    ),
    O(
        "occ_h2_06",
        P.THORNE_DEA,
        "dea",
        "medical_h2",
        "MF",
        "DEA No.",
        justification="[A-Z]{2}\\d{7}: checksum (4+7+3)+2(4+1+2)=28 -> 8 valid, registrant letter C valid; runsDEA on .medical; 'dea'/'prescriber' positives within +-5 -> 0.90 >= 0.60. Kept > 5 tokens from the (dea, medical) negatives (rx number / prescription number / pharmacy id).",
    ),
    O(
        "occ_h2_07",
        P.DEA_CHECKSUM_FAIL,
        "dea",
        "medical_h2",
        "MNF",
        "prior DEA No.",
        justification="check digit off by one -> isValidChecksum false -> rejected before scoring despite the 'DEA' label.",
    ),
    O(
        "occ_h2_08",
        P.THORNE_DEA,
        "dea",
        "medical_h2",
        "W",
        "Auth:",
        justification="the SAME valid DEA in the medication table with NO dea/prescriber/prescription/registration kw within +-5 tokens -> base 0.55 < 0.60 -> does not fire; keyword-starved valid value = watch (occ_ach_03 precedent).",
    ),
    O(
        "occ_h2_09",
        P.THORNE_NAME,
        "name",
        "medical_h2",
        "MF",
        "Attending: Dr.",
        justification="'Dr.' legal prefix -> 0.65 (the host probe does NOT tag 'Attending: Dr. Imani Thorne' on its own, so the prefix pass is the mechanism).",
        context_class="title_label",
    ),
    O(
        "occ_h2_10",
        P.CLINIC_PHONE,
        "phone",
        "medical_h2",
        "MF",
        "Clinic Phone:",
        justification="'phone' positive -> 0.80.",
    ),
    O(
        "occ_h2_11",
        P.ADDR_CLINIC,
        "address",
        "medical_h2",
        "MF",
        "",
        multiline=True,
        justification="letterhead: Title-Case 'Birch Street, Suite 2' + 'Nampa, ID 83686' -> regex arm 0.70; 2 spans.",
    ),
    O(
        "occ_h2_12",
        P.ROSALIND_MRN,
        "barcode",
        "medical_h2",
        "W",
        "",
        leg=("image",),
        justification="a REAL Code 128 symbol encoding the MRN on the specimen label: VNDetectBarcodesRequest (DRAW-2) decodes it on the page image -- an image leg the Scan text/OCR runs never take -> watch. Value = the payload; bbox = the symbol.",
    ),
    O(
        "occ_h2_13",
        P.ACCESSION_NO,
        "medicalRecord",
        "medical_h2",
        "MNF",
        "Accession No.",
        justification="'LAB-4471902' matches the MRN institution shape but sits with NO MRN positive kw within +-5 tokens -> 0.55 < 0.60.",
    ),
    O(
        "occ_h2_14",
        P.SERVICE_DATE,
        "dateOfBirth",
        "medical_h2",
        "MNF",
        "Date of Service:",
        justification="full DOBDetector base 0.05; kept > 80 chars from the 'DOB:' label -> 0.05 < 0.30 ('date of service' is not a DOB label).",
    ),
    O(
        "occ_h2_15",
        P.ICD_CODE_2,
        "other",
        "medical_h2",
        "MNF",
        "Dx:",
        justification="'I10': ICD shape, no PII shape.",
    ),
]

# ==================================================================================================
# H3 -- HR employee file, I-9-like STRUCTURE only (.financial by the employee/employer/payroll vocabulary)
# ==================================================================================================
H3 = [
    O(
        "occ_h3_01",
        P.ROSALIND_NAME,
        "name",
        "hr_h3",
        "MF",
        "Employee Name:",
        justification="clean two-token Title-Case; NLTagger host probe tags 'Employee Name: Rosalind Okafor' -> 0.70.",
    ),
    O(
        "occ_h3_02",
        P.ROSALIND_DOB,
        "dateOfBirth",
        "hr_h3",
        "MF",
        "Date of Birth:",
        justification="label-anchored numeric on .financial -> 0.85.",
    ),
    O(
        "occ_h3_03",
        P.ROSALIND_SSN,
        "ssn",
        "hr_h3",
        "MF",
        "Social Security No.:",
        source_range="synthetic + manifest",
        justification="area 487, group 62, serial 1930 valid; 'social security' positive -> 0.95. Kept > 5 tokens from 'ein' / 'account number' / 'routing number'.",
    ),
    O(
        "occ_h3_04",
        P.ROSALIND_DL,
        "driversLicense",
        "hr_h3",
        "MF",
        "Driver's License:",
        justification="label + 1L+7D -> CA gazetteer row -> 0.80 >= 0.72.",
    ),
    O(
        "occ_h3_05",
        P.ROSALIND_PASSPORT,
        "passport",
        "hr_h3",
        "MF",
        "Passport No:",
        justification="label + 1L+8D -> US ^[A-Z][0-9]{8}$ (also MX/VN) -> 0.80 >= 0.72.",
    ),
    O(
        "occ_h3_06",
        P.ADDR_ROSALIND,
        "address",
        "hr_h3",
        "MF",
        "Home Address:",
        multiline=True,
        justification="Title-Case regex arm -> 0.70; 2 spans.",
    ),
    O(
        "occ_h3_07",
        P.ROSALIND_PHONE,
        "phone",
        "hr_h3",
        "MF",
        "Home Phone:",
        justification="'phone' positive -> 0.80.",
    ),
    O(
        "occ_h3_08",
        P.ROSALIND_EMAIL,
        "email",
        "hr_h3",
        "MF",
        "Personal Email:",
        justification="RFC-2606 -> 0.90.",
    ),
    O(
        "occ_h3_09",
        P.SAMUEL_NAME,
        "name",
        "hr_h3",
        "MF",
        "Alternate Contact:",
        justification="clean two-token Title-Case; NLTagger host probe tags 'Alternate Contact: Samuel Okafor (spouse)' -> 0.70.",
    ),
    O(
        "occ_h3_10",
        P.SAMUEL_PHONE,
        "phone",
        "hr_h3",
        "MF",
        "Contact Phone:",
        justification="'phone'/'contact' positives -> 0.80.",
    ),
    O(
        "occ_h3_11",
        P.EMPLOYEE_ID,
        "medicalRecord",
        "hr_h3",
        "MNF",
        "Employee ID:",
        justification="'EMP-0048213' matches the MRN institution shape, but runsMRN is medical-only -> never runs on this .financial page (doctype-gated).",
    ),
    O(
        "occ_h3_12",
        P.HIRE_DATE,
        "dateOfBirth",
        "hr_h3",
        "MNF",
        "Hire Date:",
        justification="bare date on .financial -> suppressed (label-anchored-only gate).",
    ),
    O(
        "occ_h3_13",
        P.COST_CENTER,
        "other",
        "hr_h3",
        "MNF",
        "Cost Center:",
        justification="'4410': 4 digits, below every numeric minimum -> no candidate.",
    ),
    O(
        "occ_h3_14",
        "",
        "signatureCandidate",
        "hr_h3",
        "W",
        "Signature:",
        leg=("image",),
        justification="drawn stroke beside an exact 'Signature:' block -> DRAW-3 heuristic candidate; image leg, triage-only -> watch.",
    ),
]

# ==================================================================================================
# H4 -- payroll / benefits enrollment: direct deposit + dependents tables (.financial)
# ==================================================================================================
H4 = [
    O(
        "occ_h4_01",
        P.ROSALIND_NAME,
        "name",
        "hr_h4",
        "MF",
        "Employee:",
        justification="NLTagger host probe tags 'Employee: Rosalind Okafor' -> 0.70.",
    ),
    O(
        "occ_h4_02",
        P.ROSALIND_SSN,
        "ssn",
        "hr_h4",
        "MF",
        "SSN:",
        source_range="synthetic + manifest",
        justification="valid SSN; 'ssn' positive -> 0.95. Kept > 5 tokens from the routing/account zone (the (ssn, financial) negatives 'routing number' 0.8 / 'account number' 0.7).",
    ),
    O(
        "occ_h4_03",
        P.ROSALIND_RTN,
        "routingNumber",
        "hr_h4",
        "MF",
        "Routing Number:",
        justification="prefix 12 valid, ABA mod-10 valid; routing RUNS on .financial; 'routing' kw within +-8 tokens -> 0.88 >= 0.60; no acct kw within +-5 (so it is not also captured as an account). Group 00 -> SSN rejects.",
    ),
    O(
        "occ_h4_04",
        P.ROSALIND_ACCT_DD,
        "account",
        "hr_h4",
        "MF",
        "Account Number:",
        justification="12-digit; 'account' kw adjacent -> boosted; posterior clears 0.60 (occ_urlab_15 precedent); no routing kw within +-8.",
    ),
    O(
        "occ_h4_05",
        P.ROSALIND_ACCT_MASKED,
        "account",
        "hr_h4",
        "W",
        "Account on file:",
        masked=True,
        justification="masked X breaks the digit run -> invisible; masked watch (occ_urlab_18 precedent).",
    ),
    O(
        "occ_h4_06",
        P.EZRA_NAME,
        "name",
        "hr_h4",
        "MF",
        "Dependent:",
        justification="NLTagger host probe tags 'Dependent: Ezra Okafor' -> 0.70.",
    ),
    O(
        "occ_h4_07",
        P.EZRA_DOB,
        "dateOfBirth",
        "hr_h4",
        "MF",
        "Date of Birth:",
        justification="label-anchored numeric on .financial -> 0.85.",
    ),
    O(
        "occ_h4_08",
        P.AMARA_NAME,
        "name",
        "hr_h4",
        "MF",
        "Dependent:",
        justification="NLTagger host probe tags 'Dependent: Amara Okafor' -> 0.70.",
    ),
    O(
        "occ_h4_09",
        P.AMARA_DOB,
        "dateOfBirth",
        "hr_h4",
        "MF",
        "Date of Birth:",
        justification="label-anchored numeric on .financial -> 0.85.",
    ),
    O(
        "occ_h4_10",
        P.EMPLOYEE_NO,
        "other",
        "hr_h4",
        "MNF",
        "Employee No.",
        justification="'48213': 5 digits, below the account regex minimum of 6 -> no candidate anywhere.",
    ),
    O(
        "occ_h4_11",
        P.PLAN_CODE,
        "other",
        "hr_h4",
        "MNF",
        "Plan:",
        justification="'MED-HDHP-2': letters and a single digit -> no candidate.",
    ),
    O(
        "occ_h4_12",
        P.PAY_PERIOD_END,
        "dateOfBirth",
        "hr_h4",
        "MNF",
        "Pay Period Ending:",
        justification="bare date on .financial -> suppressed.",
    ),
    O(
        "occ_h4_13",
        P.THORNE_NPI,
        "npi",
        "hr_h4",
        "MNF",
        "Primary Care Provider NPI:",
        justification="a VALID NPI, but runsNPI is medical + foia only -> the detector never runs on this .financial page (doctype-gated). 10 digits with 'number'-free label and no phone kw within +-80 chars -> phone bare 0.60 < 0.70.",
    ),
]

# ==================================================================================================
# Registry (separate from occurrences.ALL by construction -- D12-40)
# ==================================================================================================
CAPTURE_ALL = M1 + M2 + M3 + M4 + K1 + K2 + K3 + K4 + H1 + H2 + H3 + H4
CAPTURE_BY_ID = {o.id: o for o in CAPTURE_ALL}
CAPTURE_BY_EXHIBIT: dict[str, list[O]] = {}
for _o in CAPTURE_ALL:
    CAPTURE_BY_EXHIBIT.setdefault(_o.exhibit, []).append(_o)

if len(CAPTURE_BY_ID) != len(CAPTURE_ALL):
    raise ValueError("duplicate occurrence id in the capture registry")

# the exhibit -> `31-` SSC.1 page class map (C2 mail/forms, C3 court/FOIA, C4 medical/HR)
EXHIBIT_CLASS = {
    "mail_m1": "C2",
    "mail_m2": "C2",
    "forms_m3": "C2",
    "forms_m4": "C2",
    "court_k1": "C3",
    "court_k2": "C3",
    "court_k3": "C3",
    "court_k4": "C3",
    "medical_h1": "C4",
    "medical_h2": "C4",
    "hr_h3": "C4",
    "hr_h4": "C4",
}
# the doctype each page is DESIGNED to classify as (asserted by acceptance SS14 against the real sets)
EXHIBIT_DOCTYPE = {
    "mail_m1": "financial",
    "mail_m2": "financial",
    "forms_m3": "financial",
    "forms_m4": "generic",
    "court_k1": "court",
    "court_k2": "court",
    "court_k3": "foia",
    "court_k4": "court",
    "medical_h1": "medical",
    "medical_h2": "medical",
    "hr_h3": "financial",
    "hr_h4": "financial",
}
