#!/usr/bin/env python3
"""T3.1 — build the search-GT query bank (search-ground-truth/search-queries.json).

Deterministic generator for the Family-3 search-correctness baseline (1.2
measurement design §3): a query bank seeded from packet-ground-truth.json
values plus targeted normalization probes, crossed with a pairwise-covering
set of option vectors over the NINE SearchOptions toggles
(caseSensitive wholeWord includeOCR normalizeUnicode exactMatch
stripDigitSeparators normalizeSmartPunctuation foldDiacritics
multiTermConjunction).

The pairwise set is generated by a small deterministic greedy all-pairs
builder (no external PICT dependency): the seed rows are the all-defaults
vector plus the nine one-factor flips, then greedy fill until every
unordered toggle pair covers all four value combinations (36 pairs x 4 =
144 pair-values).

The bank is SELF-VERIFYING: every literal query tagged with a nonzero
`packet_text_occurrences` expectation is counted against the live packet
text at build time (PyMuPDF); a mismatch aborts the build. Counts are
provenance, not ground truth — the GT sidecars are frozen separately from
the H3.1 runner + H3.2 differential-oracle adjudication.

No dates, no randomness: output is byte-stable for a given packet.pdf.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import pymupdf

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "search-ground-truth"
OUT_PATH = OUT_DIR / "search-queries.json"

TOGGLES = [
    "caseSensitive",
    "wholeWord",
    "includeOCR",
    "normalizeUnicode",
    "exactMatch",
    "stripDigitSeparators",
    "normalizeSmartPunctuation",
    "foldDiacritics",
    "multiTermConjunction",
]

# SearchOptions defaults (Models/SearchTypes.swift): includeOCR,
# normalizeUnicode, normalizeSmartPunctuation default true.
DEFAULTS = {
    "caseSensitive": False,
    "wholeWord": False,
    "includeOCR": True,
    "normalizeUnicode": True,
    "exactMatch": False,
    "stripDigitSeparators": False,
    "normalizeSmartPunctuation": True,
    "foldDiacritics": False,
    "multiTermConjunction": False,
}


def vector_bits(vec: dict) -> tuple:
    return tuple(vec[t] for t in TOGGLES)


def pairs_of(bits: tuple):
    n = len(bits)
    for i in range(n):
        for j in range(i + 1, n):
            yield (i, j, bits[i], bits[j])


# Semantics-driven two-flip vectors: the pairwise criterion alone lands every
# off-default pair in the single anti-default complement row, so two-factor
# interactions are otherwise never observed in near-default context. These
# rows target the engine's actual interaction seams (offset-map composition,
# base-coordinate word boundaries, NFKC-before-smart-punct ordering, the OCR
# extension path, the exactMatch/wholeWord equivalence).
SEMANTIC_DUALS = [
    ("caseSensitive", "wholeWord"),
    ("exactMatch", "wholeWord"),
    ("foldDiacritics", "stripDigitSeparators"),  # composed offset maps
    ("wholeWord", "stripDigitSeparators"),  # boundary check in base coords
    ("normalizeUnicode", "normalizeSmartPunctuation"),  # q24 interaction
    ("caseSensitive", "normalizeUnicode"),
    ("includeOCR", "stripDigitSeparators"),  # OCR-leg extension path
    ("wholeWord", "normalizeSmartPunctuation"),
]


def build_pairwise_vectors() -> list[dict]:
    """Deterministic greedy all-pairs set, seeded with default + one-flips."""
    seed_rows = [dict(DEFAULTS)]
    for t in TOGGLES:
        row = dict(DEFAULTS)
        row[t] = not row[t]
        seed_rows.append(row)

    covered: set = set()
    chosen: list[dict] = []
    for row in seed_rows:
        chosen.append(row)
        covered.update(pairs_of(vector_bits(row)))

    all_pairs = {
        (i, j, a, b)
        for i in range(len(TOGGLES))
        for j in range(i + 1, len(TOGGLES))
        for a in (False, True)
        for b in (False, True)
    }

    # Greedy fill: enumerate all 512 vectors in fixed binary order; on each
    # round pick the lowest-index vector covering the most missing pairs.
    universe = []
    for k in range(512):
        bits = tuple(bool((k >> (8 - i)) & 1) for i in range(9))
        universe.append(bits)

    while covered != all_pairs:
        best_bits = None
        best_gain = -1
        for bits in universe:
            gain = len(set(pairs_of(bits)) - covered)
            if gain > best_gain:
                best_gain = gain
                best_bits = bits
        if best_gain <= 0:
            break
        covered.update(pairs_of(best_bits))
        chosen.append({t: best_bits[i] for i, t in enumerate(TOGGLES)})

    for a, b in SEMANTIC_DUALS:
        row = dict(DEFAULTS)
        row[a] = not row[a]
        row[b] = not row[b]
        if vector_bits(row) not in {vector_bits(c) for c in chosen}:
            chosen.append(row)
            covered.update(pairs_of(vector_bits(row)))

    vectors = []
    dual_names = {}
    for a, b in SEMANTIC_DUALS:
        row = dict(DEFAULTS)
        row[a] = not row[a]
        row[b] = not row[b]
        dual_names[vector_bits(row)] = f"dual-{a}-{b}"
    for idx, row in enumerate(chosen):
        bits = vector_bits(row)
        if idx == 0:
            vid = "v00-default"
        elif idx <= 9:
            vid = f"v{idx:02d}-flip-{TOGGLES[idx - 1]}"
        elif bits in dual_names:
            vid = f"v{idx:02d}-{dual_names[bits]}"
        else:
            vid = f"v{idx:02d}-pair"
        vectors.append({"id": vid, "options": {t: row[t] for t in TOGGLES}})
    missing = all_pairs - covered
    return vectors, len(all_pairs), len(all_pairs) - len(missing)


# ---------------------------------------------------------------------------
# Query bank. Families:
#   gt-value          — verbatim value from packet-ground-truth.json
#   case-variant      — case-changed twin of a gt value
#   substring         — proper substring of corpus tokens (wholeWord probe)
#   separator-variant — separator-stripped/altered twin (stripDigitSeparators)
#   smartpunct-probe  — query-side typographic characters (fold interactions)
#   absent-control    — value absent from every document (expected 0 hits)
#   regex-shape       — realistic user pattern
#   regex-twin        — regex-escaped literal twin of a text query
#   regex-invalid     — non-compiling pattern (expected: empty result stream)
#   regex-pathological— ReDoS shape (precheck-rejected; expected empty)
#   multiterm         — term lists probing OR/AND page semantics
# `expect_packet_occurrences` (literal text queries only) = verbatim
# case-sensitive raw-text count, verified at build time. None = not checked.
# ---------------------------------------------------------------------------


def build_queries() -> list[dict]:
    q = []

    def text(qid, query, family, notes, occ=None):
        q.append(
            {
                "qid": qid,
                "mode": "text",
                "query": query,
                "family": family,
                "notes": notes,
                "expect_packet_occurrences": occ,
            }
        )

    def regex(qid, pattern, family, notes):
        q.append(
            {
                "qid": qid,
                "mode": "regex",
                "pattern": pattern,
                "family": family,
                "notes": notes,
                "expect_packet_occurrences": None,
            }
        )

    def multi(qid, terms, family, notes):
        q.append(
            {
                "qid": qid,
                "mode": "multiTerm",
                "terms": terms,
                "family": family,
                "notes": notes,
                "expect_packet_occurrences": None,
            }
        )

    # --- literal text: names -------------------------------------------------
    text("q01", "Hartwell", "gt-value", "surname token, multi-page", 14)
    text("q02", "Delia Hartwell", "gt-value", "two-token name", 6)
    text("q03", "Delia R. Hartwell", "gt-value", "name with middle initial + period", 4)
    text("q04", "DELIA HARTWELL", "case-variant", "all-caps twin of q02 (caseSensitive probe)", 9)
    text("q05", "delia hartwell", "case-variant", "lowercase twin of q02 (0 verbatim)", 0)
    text("q06", "Hart", "substring", "prefix of Hartwell (wholeWord probe)", None)
    text("q07", "well", "substring", "suffix substring of Hartwell (wholeWord probe)", None)
    text("q34", "Karen Delgado", "gt-value", "second-borrower name, page 1", 1)
    text("q35", "Mateo Hartwell", "gt-value", "dependent name", 2)
    text("q36", "MATEO HARTWELL", "case-variant", "all-caps twin of q35", 2)
    text("q40", "Wrenfield", "gt-value", "street-name token, multi-page", None)

    # --- literal text: ids / numbers ----------------------------------------
    text("q08", "502-19-7438", "gt-value", "primary SSN, dashed", 3)
    text(
        "q09",
        "502197438",
        "separator-variant",
        "SSN digits only — matches q08's value only with stripDigitSeparators",
        0,
    )
    text("q10", "XXX-XX-7438", "gt-value", "masked SSN render", 2)
    text("q11", "970-72 5518", "gt-value", "ITIN with mixed dash/space separators", 1)
    text("q12", "970725518", "separator-variant", "ITIN digits only (strip probe)", 0)
    text("q31", "36-4419872", "gt-value", "EIN, dashed", 2)
    text("q32", "1364419872", "gt-value", "10-digit EIN-shaped value present verbatim", None)
    text(
        "q33",
        "364419872",
        "separator-variant",
        "EIN digits only — strip-on matches 36-4419872; ALSO a verbatim substring "
        "of the distinct value 1364419872 (strip-off still hits that suffix)",
        None,
    )
    text("q17", "4111 1111 1111 1111", "gt-value", "credit card, space-grouped", 1)
    text("q18", "4111111111111111", "separator-variant", "card digits only (strip probe)", 0)
    text(
        "q19",
        "620000",
        "separator-variant",
        "SO-01 comma+decimal probe: matches '6,200.00' only with strip on "
        "(comma and period are both in the separator set)",
        0,
    )
    text("q29", "N42851960", "gt-value", "passport value", 1)
    text("q30", "88KJ2", "gt-value", "short plate value", 1)
    text("q22", "6ABC123", "gt-value", "plate decoy value (search is category-blind)", 1)
    text(
        "q27",
        "19",
        "substring",
        "two-digit token: whole-word matches INSIDE 502-19-7438 (dashes are "
        "non-alnum boundaries) — boundary-rule pin",
        None,
    )

    # --- literal text: contact / address ------------------------------------
    text("q13", "(208) 555-0147", "gt-value", "phone, parenthesized", 1)
    text(
        "q14",
        "2085550147",
        "separator-variant",
        "phone digits only — parens are NOT in the separator set, so strip-on "
        "must still MISS (208) 555-0147; separator-set boundary pin",
        0,
    )
    text("q15", "208.555.0119", "gt-value", "phone, dot-separated", 1)
    text(
        "q16",
        "2085550119",
        "separator-variant",
        "phone digits only — strip-on matches 208.555.0119 (dots strip)",
        0,
    )
    text("q37", "d.hartwell@example.net", "gt-value", "email with dots", 2)
    text("q20", "4127 Wrenfield Place", "gt-value", "street fragment", None)
    text("q21", "Boise, ID 83702", "gt-value", "city-state-zip fragment", None)
    text(
        "q26",
        "ID",
        "substring",
        "state code — collides with substrings only at alnum boundaries "
        "(wholeWord discriminator across many pages)",
        None,
    )
    text(
        "q38",
        "PO Box 2215",
        "separator-variant",
        "unpunctuated twin of 'P.O. Box 2215' — matches only with strip on "
        "(periods+spaces strip from both sides)",
        0,
    )
    text("q39", "P.O. Box 2215", "gt-value", "boxed mailing address", 1)

    # --- smart-punctuation query-side probes ---------------------------------
    text(
        "q24",
        "502‑19‑7438",
        "smartpunct-probe",
        "NON-BREAKING HYPHEN query: NFKC(U+2011)=U+2010 which the smart-punct "
        "map does NOT fold — expected to match ONLY when normalizeUnicode is "
        "OFF and normalizeSmartPunctuation is ON (interaction pin)",
        0,
    )
    text(
        "q25",
        "502–19–7438",
        "smartpunct-probe",
        "EN DASH query: U+2013 survives NFKC and the map folds it to '-' — "
        "matches whenever normalizeSmartPunctuation is ON",
        0,
    )
    text(
        "q28",
        "Hartwell,",
        "separator-variant",
        "trailing comma: strip-on removes the comma from the QUERY too, "
        "degenerating to plain 'Hartwell' (separator strip is not "
        "digit-scoped) — semantics pin",
        None,
    )

    # --- absent controls ------------------------------------------------------
    text("q23", "ZEBRA-QUARTZ-9911", "absent-control", "never present, all modes", 0)
    text("q41", "Loan", "gt-value", "common document word (dense-hit row)", None)

    # --- regex ---------------------------------------------------------------
    regex(
        "r01",
        "\\d{3}-\\d{2}-\\d{4}",
        "regex-shape",
        "SSN/ITIN dashed shape (masked XXX rows must NOT hit)",
    )
    regex("r02", "Hartwell", "regex-twin", "literal-as-regex twin of q01")
    regex(
        "r03",
        "502-19-7438",
        "regex-twin",
        "escaped twin of q08 (no metacharacters — identical string)",
    )
    regex("r04", "\\d{3}[-.]\\d{3}[-.]\\d{4}", "regex-shape", "US phone with dash or dot groups")
    regex(
        "r05",
        "(\\d{3}\\) \\d{3}-\\d{4}",
        "regex-invalid",
        "unbalanced parenthesis — must not compile; empty stream",
    )
    regex("r06", "\\d+", "regex-shape", "digit runs (dense-hit / cap probe)")
    regex(
        "r07",
        "(?i)hartwell",
        "regex-shape",
        "inline case-insensitivity flag (engine passes pattern verbatim)",
    )
    regex(
        "r08",
        "Delia\\s+R\\.\\s+Hartwell",
        "regex-shape",
        "whitespace-class name (newline-crossing probe)",
    )
    regex(
        "r09",
        "\\bID\\b",
        "regex-shape",
        "\\b word-boundary twin of q26+wholeWord (near-equivalence relation)",
    )
    regex(
        "r10",
        "4111(\\s?\\d{4}){3}",
        "regex-shape",
        "credit card with optional space groups (bounded quantifier)",
    )
    regex("r11", "\\d{2}/\\d{2}/\\d{4}", "regex-shape", "mm/dd/yyyy dates")
    regex(
        "r12",
        "(a+)+b",
        "regex-pathological",
        "classic ReDoS shape — precheck-rejected; empty stream (H3.4 tie-in)",
    )

    # --- multiTerm -----------------------------------------------------------
    multi(
        "m01",
        ["Hartwell", "Boise"],
        "multiterm",
        "overlapping page sets: AND = intersection pages, OR = union",
    )
    multi(
        "m02",
        ["Delgado", "Modesto"],
        "multiterm",
        "disjoint page sets (Delgado p1, Modesto p0): AND must be empty",
    )
    multi(
        "m03",
        ["Hartwell", "ZEBRA-QUARTZ-9911"],
        "multiterm",
        "absent conjunct: AND empty everywhere, OR = Hartwell hits",
    )
    multi(
        "m04",
        ["502-19-7438", "970-72-5518", "078-05-1120"],
        "multiterm",
        "three dashed ids (co-page probe)",
    )
    multi(
        "m05",
        ["Boise", "Meridian", "Modesto"],
        "multiterm",
        "three cities, partially overlapping pages",
    )
    multi("m06", ["Hart", "well"], "multiterm", "substring terms x wholeWord interplay")
    multi("m07", ["Hartwell", ""], "multiterm", "empty term in the list (filtering semantics pin)")
    multi(
        "m08",
        ["DELIA HARTWELL", "d.hartwell@example.net"],
        "multiterm",
        "case-variant + email pair (caseSensitive interplay)",
    )

    return q


METAMORPHIC = {
    "literal_regex_twins": [["q01", "r02"], ["q08", "r03"]],
    "case_variant_sets": [["q02", "q04", "q05"], ["q35", "q36"]],
    "strip_pairs": [
        ["q09", "q08"],
        ["q12", "q11"],
        ["q16", "q15"],
        ["q18", "q17"],
    ],
    "wholeword_regex_near_twin": [["q26", "r09"]],
    "relations": [
        "case-insensitive hits are a superset of case-sensitive hits (same query)",
        "diacritic-folded hits are a superset of unfolded hits (same query)",
        "whole-word hits are a subset of substring hits (same query)",
        "multiTerm AND hit pages are a subset of OR hit pages (same terms)",
        "a literal's text-mode hits equal the escaped literal's regex-mode hits",
        "exactMatch and wholeWord produce identical hit sets on text/multiTerm/OCR paths",
    ],
    "expected_inert": {
        "packet_text_leg": ["normalizeUnicode", "foldDiacritics", "includeOCR"],
        "packet_text_leg_note": "packet text is pure ASCII and all pages are rich; "
        "NFKC, diacritic fold and the OCR toggle must not change hit sets — "
        "EXCEPT queries carrying non-ASCII characters (q24/q25), where "
        "normalizeUnicode participates by design.",
        "regex_mode": [
            "caseSensitive",
            "exactMatch",
            "stripDigitSeparators",
            "foldDiacritics",
            "multiTermConjunction",
        ],
        "regex_mode_note": "the regex path never case-folds, never applies the "
        "length-changing extensions, ignores exactMatch, and conjunction "
        "only affects multiTerm.",
        "text_regex_single_mode": ["multiTermConjunction"],
    },
}


def verify_counts(queries: list[dict]) -> None:
    doc = pymupdf.open(ROOT / "packet.pdf")
    pages = [p.get_text() for p in doc]
    failures = []
    for row in queries:
        expected = row.get("expect_packet_occurrences")
        if expected is None or row["mode"] != "text":
            continue
        got = sum(t.count(row["query"]) for t in pages)
        if got != expected:
            failures.append(f"{row['qid']}: expected {expected} verbatim, counted {got}")
    if failures:
        sys.exit(
            "build_search_queries: verbatim-count verification FAILED:\n  " + "\n  ".join(failures)
        )


def main() -> None:
    vectors, pairs_total, pairs_covered = build_pairwise_vectors()
    queries = build_queries()
    verify_counts(queries)

    packet_sha = hashlib.sha256((ROOT / "packet.pdf").read_bytes()).hexdigest()
    scan_sha = hashlib.sha256(
        (ROOT / "variants" / "packet-scan-sim-150dpi.pdf").read_bytes()
    ).hexdigest()

    out = {
        "schema_version": 1,
        "generated_by": "resecta-sample-doc/tools/build_search_queries.py",
        "toggles": TOGGLES,
        "defaults": DEFAULTS,
        "vectors": vectors,
        "pair_coverage": {"pairs_total": pairs_total, "pairs_covered": pairs_covered},
        "docs": {
            "packet": {"path": "packet.pdf", "sha256": packet_sha},
            "packet-scan-sim-150dpi": {
                "path": "variants/packet-scan-sim-150dpi.pdf",
                "sha256": scan_sha,
            },
        },
        "queries": queries,
        "metamorphic": METAMORPHIC,
    }

    OUT_DIR.mkdir(exist_ok=True)
    OUT_PATH.write_text(json.dumps(out, indent=1, sort_keys=True, ensure_ascii=True) + "\n")
    n_by_mode = {}
    for row in queries:
        n_by_mode[row["mode"]] = n_by_mode.get(row["mode"], 0) + 1
    print(
        f"wrote {OUT_PATH.relative_to(ROOT)}: {len(vectors)} vectors "
        f"(pairs {pairs_covered}/{pairs_total}), {len(queries)} queries {n_by_mode}"
    )


if __name__ == "__main__":
    main()
